# Generated by Django 4.1.3 on 2023-08-01 12:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BoletimGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portarias_fks', models.CharField(default='', max_length=1000)),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo_pdf', models.CharField(default='', max_length=100000)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('revisao', 'Revisão'), ('aprovado', 'Aprovado')], default='revisao', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Composicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usario', models.CharField(max_length=80, verbose_name='Usuario')),
                ('sigla_setor', models.CharField(max_length=20, verbose_name='sigla do setor')),
                ('nome_setor', models.CharField(max_length=80, verbose_name='nome do setor')),
                ('tipo_ato', models.CharField(choices=[('portaria', 'Portaria'), ('resolucao', 'Resolução'), ('boletim', 'Boletim')], max_length=10, verbose_name='Tipo de Ato Normativo')),
            ],
        ),
        migrations.CreateModel(
            name='AtoNormativ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime(2000, 10, 10, 4, 0, tzinfo=datetime.timezone.utc), verbose_name='Data de criação')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Número')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('doe_data', models.DateTimeField(auto_now_add=True, verbose_name='Data do Diário Oficial')),
                ('doe_numero', models.PositiveIntegerField(null=True, verbose_name='Número do Diário Oficial')),
                ('doe_secao', models.CharField(max_length=40, verbose_name='Seção do Diário Oficial')),
                ('doe_pagina', models.CharField(max_length=40, verbose_name='Página do Diário Oficial')),
                ('dt_cadastro', models.DateTimeField(default=datetime.datetime(2000, 10, 10, 4, 0, tzinfo=datetime.timezone.utc), verbose_name='Data de cadastro')),
                ('usr_cadastro', models.CharField(default='enzo', max_length=40, verbose_name='Usuário de cadastro')),
                ('ementa', models.TextField(max_length=400, verbose_name='Ementa')),
                ('texto_normativo', models.TextField(default='escrever', max_length=1000, verbose_name='Texto normativo')),
                ('publicado', models.CharField(default='n', max_length=1, verbose_name='Publicado')),
                ('dt_alteracao', models.DateField(auto_now=True, verbose_name='Data de alteração')),
                ('usr_alteracao', models.CharField(max_length=20, verbose_name='Usuário de alteração')),
                ('dt_publicado', models.DateField(blank=True, null=True, verbose_name='Data de publicação')),
                ('usr_publicacao', models.CharField(max_length=45, verbose_name='Usuário de publicação')),
                ('autoridade1', models.CharField(default='setor', max_length=45, verbose_name='Autoridade 1')),
                ('autoridade2', models.CharField(default='setor', max_length=45, null=True, verbose_name='Autoridade 2')),
                ('status', models.CharField(choices=[('revisao', 'Revisão'), ('aprovado', 'Aprovado'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado')], default='revisao', max_length=10)),
                ('tipo_ato', models.CharField(max_length=45, null=True, verbose_name='ato')),
                ('assinante1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ato_normativ_assinante1', to='core.autoridade', verbose_name='Assinante 1')),
                ('assinante2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ato_normativ_assinante2', to='core.autoridade', verbose_name='Assinante 2')),
            ],
        ),
    ]
